### ISSUE TITLE
Release a version compatible with standard-library 1.7 and Agda 2.6.2

### ISSUE THREAD

**Issue by turion** [ryanorendorff/functional-linear-algebra#40]
Currently the version is pinned to 1.6, which gives this error message if you try to build with 1.7:

```
 Library 'standard-library-1.6' not found.
```

**Comment by turion** [comment]
It seems no code changes are necessary. Your library compiles with 1.7 as well. Maybe the best idea is to remove the restrictive upper bound, and you'll be notified via nixpkgs when something breaks?

**Comment by ryanorendorff** [comment]
Thanks for checking! I was planning on validating and making the change tonight, so should be before that 7 day window. 

I think you are right on the upper bound part. I’ll just make it generic to the version.

**Comment by ryanorendorff** [comment]
PR #41 should handle this  (upper bound  removed). Once the tests pass, I'll merge, tag  with v0.4,  and then put up a PR in nixpkgs reflecting the update.

**Comment by ryanorendorff** [comment]
@turion See https://github.com/NixOS/nixpkgs/pull/131634 for the nixpkgs PR that includes the fix.
